### PR TITLE
fix decorator detection bug

### LINKED ISSUE #49: 3.11 decorator detection bug
```python
import inspect

import executing

frame = inspect.currentframe()


class Tester:
    def __call__(self, f):
        deco(f)


tester = Tester()


def deco(f):
    assert f.__name__ == 'foo'
    ex = executing.Source.executing(frame)
    print(f"{ex.node = }\n{ex.decorator = }\n")


for d in [deco, tester]:
    @d
    def foo():
        pass
```

3.10 output:

```
ex.node = <ast.FunctionDef object at 0x7f9c7e65b1c0>
ex.decorator = <ast.Name object at 0x7f9c7e65a2f0>

ex.node = <ast.FunctionDef object at 0x7f9c7e65b1c0>
ex.decorator = <ast.Name object at 0x7f9c7e65a2f0>
```

3.11 output:

```
ex.node = <ast.Name object at 0x7fd9fe5a96f0>
ex.decorator = None

ex.node = <ast.FunctionDef object at 0x7fd9fe5a9780>
ex.decorator = <ast.Name object at 0x7fd9fe5a96f0>
```

Somehow, the decorator is only detected when it's an object with `__call__`. When it's just a function, executing sets `decorator` to `None` and `node` to the decorator instead of the function definition. This is REALLY weird.

### PR DESCRIPTION
**Pull request by 15r10nk**
try to fix #49

I also reported `frame.f_lasti` and the problem is that the instruction is a `CACHE` instruction in the `deco` case (`f_lasti == 130`).

The Tester case gets the expected instruction and maps the bytecode correctly.

You can find my source here https://github.com/15r10nk/executing/tree/decorator-detection-bug

grafik

I could ignore CACHE instructions until now. I will try to figure out what they are good for.

### CODE REVIEW

**Comment by 15r10nk** [comment]
> Logically, this space is part of the preceding instruction. Many opcodes expect to be followed by an exact number of caches, and will instruct the interpreter to skip over them at runtime.

using the real instruction before the `CACHE` seems to work

**Comment by 15r10nk** [comment]
This should fix the bug. I also added analyse.py which is very useful for debugging executing. @alexmojaki please tell me if it can stay there or should I move it somewhere else?

**Comment by alexmojaki** [comment]
> can I disable that the pipeline runs for every commit of a merge-request? I don't want to waste resources.

When would it run for a PR then?

> This should fix the bug.

Awesome, thanks! Do you understand the deal with CACHE? Do you think there should be a CPython issue?

> I also added analyse.py which is very useful for debugging executing. @alexmojaki please tell me if it can stay there or should I move it somewhere else?

It looks great, let's keep it. Do you think putting it under the tests folder would make sense?

**Comment by 15r10nk** [comment]
I created a draft-pull request and did not expected the pipeline to run. It is not a big problem I can also use [skip ci] in the commit message. 
I am also quiet new to github and I dont know how things usually work her.


CACHE is documented [here](https://docs.python.org/3.11/library/dis.html#opcode-CACHE). The documentation says only that it stores something and that it behaves like an NOP.

I think it is an issue because it is documented that the interpreter should step over CACHE instructions. Do you want to report it or should I?

**Comment by alexmojaki** [comment]
Please report it

**Comment by alexmojaki** [comment]
Is this PR still a draft?

**Comment by 15r10nk** [comment]
created this bug report and added it as a comment to the work around https://github.com/python/cpython/issues/96970.

no draft any more

**Comment by alexmojaki** [comment]
Thanks!

**Pull request merged**
